name: weather_app
description: A PDF editor app with e-signature capabilities, document editing, and cloud storage integration.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  file_picker: ^8.1.2
  firebase_storage: ^12.1.0
  pdfx: ^2.6.0
  pdf: ^3.11.1
  printing: ^5.13.4
  syncfusion_flutter_pdfviewer: ^28.1.39
  syncfusion_flutter_pdf: ^28.1.39
  image: ^4.2.0
  path: ^1.9.0
  cloud_firestore: ^5.4.0
  http: ^1.2.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_dotenv: ^5.1.0
  signature: ^5.5.0
  path_provider: ^2.0.15
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
